# Generated by Django 5.1.15 on 2026-10-03 09:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(help_text='3-character uppercase unique IATA airport identifier (e.g., DEL, BOM, BLR)', max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='IATA code must be exactly 3 uppercase letters (e.g., DEL, BOM, BLR).', regex='^[A-Z]{3}$')])),
                ('city_name', models.CharField(help_text='Associated metropolitan area or city name', max_length=100)),
                ('metro_tier', models.CharField(choices=[('T1', 'Tier 1 Metro'), ('T2', 'Tier 2 Regional Hub')], default='T1', help_text='Hub classification for demographic and traffic clustering', max_length=2)),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
                'ordering': ['iata_code'],
            },
        ),
        migrations.CreateModel(
            name='DailyCPIIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateField(help_text='Date for which the daily Laspeyres index is computed', unique=True)),
                ('laspeyres_index_value', models.FloatField(help_text='Base 100.0 Laspeyres airfare index value for the day')),
                ('inflation_rate_mom', models.FloatField(help_text='Month-over-month (MoM) inflation percentage change')),
                ('total_observations_analyzed', models.PositiveIntegerField(help_text='Total number of valid fare observations ingested in this computation')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this daily metric record was compiled and stored')),
            ],
            options={
                'verbose_name': 'Daily CPI Index',
                'verbose_name_plural': 'Daily CPI Indices',
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='FlightRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_traffic_weight', models.FloatField(default=1.0, help_text='Statistical weight (w_i) used in Laspeyres CPI basket index calculation')),
                ('base_benchmark_fare', models.DecimalField(decimal_places=2, default=Decimal('4500.00'), help_text='Benchmark baseline fare (p_0) in INR for CPI price relatives', max_digits=10)),
                ('destination', models.ForeignKey(help_text='Arrival airport', on_delete=django.db.models.deletion.CASCADE, related_name='arriving_routes', to='indexer.airport')),
                ('origin', models.ForeignKey(help_text='Departure airport', on_delete=django.db.models.deletion.CASCADE, related_name='departing_routes', to='indexer.airport')),
            ],
            options={
                'verbose_name': 'Flight Route',
                'verbose_name_plural': 'Flight Routes',
                'ordering': ['origin__iata_code', 'destination__iata_code'],
                'unique_together': {('origin', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='FareObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('INDIGO', 'IndiGo'), ('AIRINDIA', 'Air India'), ('SPICEJET', 'SpiceJet'), ('AKASA', 'Akasa Air')], help_text='Airline operating the service', max_length=20)),
                ('source_portal', models.CharField(choices=[('DIRECT', 'Direct Airline Portal'), ('MAKEMYTRIP', 'MakeMyTrip'), ('EASEMYTRIP', 'EaseMyTrip'), ('YATRA', 'Yatra')], help_text='Distribution channel or OTA portal where fare was observed', max_length=20)),
                ('observed_price_inr', models.DecimalField(decimal_places=2, help_text='Observed one-way fare inclusive of baseline taxes in INR', max_digits=10)),
                ('departure_date', models.DateField(help_text='Scheduled departure date for the fare quote')),
                ('advance_booking_days', models.PositiveIntegerField(help_text='Advance booking window in days (e.g., 1, 7, 14, 30 days out)')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the fare observation was scraped/recorded')),
                ('route', models.ForeignKey(help_text='Flight route for this observation', on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='indexer.flightroute')),
            ],
            options={
                'verbose_name': 'Fare Observation',
                'verbose_name_plural': 'Fare Observations',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['route', 'departure_date'], name='indexer_far_route_i_a351ad_idx'), models.Index(fields=['carrier', 'scraped_at'], name='indexer_far_carrier_b61c50_idx')],
            },
        ),
    ]
