# Generated by Django 5.1.15 on 2026-10-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Geographical latitude coordinate', null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Geographical longitude coordinate', null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='state_name',
            field=models.CharField(blank=True, default='', help_text='State or Union Territory location', max_length=60),
        ),
        migrations.AddField(
            model_name='dailycpiindex',
            name='metro_sub_index',
            field=models.FloatField(default=100.0, help_text='Laspeyres price index value for Tier 1 Metro corridors'),
        ),
        migrations.AddField(
            model_name='dailycpiindex',
            name='regional_sub_index',
            field=models.FloatField(default=100.0, help_text='Laspeyres price index value for Tier 2/3 UDAN regional corridors'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='metro_tier',
            field=models.CharField(choices=[('T1', 'Tier 1 Metro'), ('T2', 'Tier 2 Commercial Hub'), ('T3', 'Tier 3 Regional / UDAN')], default='T1', help_text='Hub classification for demographic and traffic clustering', max_length=2),
        ),
    ]
